services:
  mysql:
    container_name: mysql
    image: arm64v8/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABSE: crossed_roads

    volumes:
      - ./data/mysql:/data/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped