spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://10.16.6.25:3306/crossed_roads
    username: root
    password: 12345678
    pool-size: 30

  data:
    elasticsearch:
      cluster-node: localhost:9200

server:
  error:
    include-binding-errors: always
    include-message: always
